Staging
Revature-Cinephiliacs/ForumRepo pull request #14
Opened 2021-04-21 20:13 UTC by Kugelsicher

2021-04-21 20:29 UTC, nicholasvvong requested changes
Comments on DTO models stating they're DTO models for frontend. Possible comments on repo models stating they're for backend. Some of the RepoLogic methods missing XML comments

2021-04-21 21:15 UTC, nicholasvvong commented on Logic/ForumLogic.cs
> +     /// </summary>
All of the comments for this class is in the interface

2021-04-21 22:07 UTC, nicholasvvong approved these changes
Changes look good. Comments have been added to the missing functions/classes.

2021-04-22 15:12 UTC, markmoorerev approved these changes

2021-04-22 15:12 UTC, merged